#!/usr/bin/python3

import sys

sys.path.append('src/client')
sys.path.append('src/client/core')
sys.path.append('src/client/gui')
sys.path.append('src/client/ai')

from ZappyClient import ZappyClient

if __name__ == "__main__":
    zappy = ZappyClient()
